version: '3.9'
services:
  frontend:
    container_name: project_alexey_antipin
    image: stierlitz2023/project
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '3000:3000'
